version: '3.4'

services:
  prometheus:
    image: prom/prometheus:v2.37.9
    user: root
    container_name: prometheus
    hostname: prometheus
    restart: always
    volumes:
      - ./prometheus/:/etc/prometheus
      - ./prometheus/data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    ports:
      - 9090:9090  
    networks:
      - monitoring
  
  grafana:
    image: grafana/grafana:10.4.2
    container_name: grafana
    hostname: grafana
    restart: always
    environment:
      -  GF_SECURITY_ADMIN_PASSWORD=admin123
    volumes:
    - ./grafana:/var/lib/grafana
    ports:
      - 3000:3000
    depends_on:
      - prometheus
    networks:
      - monitoring
  
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"  
      - "15672:15672" 
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin123
    networks:
      - monitoring
    volumes:
      - ./rabbitmq:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 3

networks:
  monitoring:
    driver: bridge